baseURL: 'https://matthewc.dev/'
languageCode: 'en-us'
title: 'Matthew C Dev'
theme: papermod
enableEmoji: true
paginate: 10
enableGitInfo: true
publishdir: 'docs'
buildFuture: true
enableRobotsTXT: true
timeout: 60000

frontmatter:
  date:
  - publishDate
  - :git
  - date
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Matthew Carlson
  description: "Matthew Carlson's Personal Website"
  author: Me
  mainSections: ['projects', 'musings']
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Matthew Carlson"
    icon: /logo.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi \U0001F44B, I'm Matthew Carlson"
    Content: I'm a firmware engineer at <i class="fa-brands fa-apple"></i> Apple, <i class="fa-solid fa-hammer"></i> a woodworker , and <i class="fa-solid fa-fire-burner"></i> a baker
    imageUrl: /face.jpg

  socialIcons:
    - name: twitter
      url: "https://twitter.com/matthewfcarlsonHD"
    - name: medium
      url: "https://medium.com/@matthewfcarlson"
    - name: github
      url: "https://github.com/matthewfcarlson"
    - name: hackaday
      url: "https://hackaday.com/author/matthewcarlson/"
    - name: linkedin
      url: "https://www.linkedin.com/in/matthewfcarlson"

  analytics:
    google:
      SiteVerificationTag: "56rW1rUI4LWedkHQTqbYEQ1DHqRwd8GqLln3Pg8FI-o"
    bing:
      SiteVerificationTag: "0764BC2BC3D20B77B39F91E88453504E"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true

  editPost:
    URL: "https://github.com/matthewfcarlson/matthewfcarlson.github.io/issues/new?body=Your+issue+here%0A%0A%0A---%0AI%27m+a+human.+Please+be+nice.&title=Issue with "
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:

    - identifier: musings
      name: musings
      url: /musings/
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 10
    - identifier: resume
      name: resume
      url: https://www.linkedin.com/in/matthewfcarlson
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30
    - identifier: blender
      name: blender
      url: /blender/
      weight: 15
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
# Read: https://github.com/adityatelange/hugo-papermod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true