blank_issues_enabled: false
contact_links:
  - name: papermod Discussions
    url: https://github.com/adityatelange/hugo-papermod/discussions
    about: Please ask and answer questions/doubts here, do not open an issue for questions.
